### ISSUE TITLE
If/Else statement 

### ISSUE THREAD

**Issue by JinWon01** [bennuttall/python-intro#1]
everytime i type in the word 'else' it gives me a syntaxError: invalid syntax
please advise. thanks!

**Comment by bennuttall** [comment]
Are you using a colon after `if` and `else`?

The following is correct:

``` python
if something:
    something()
else:
    something_else()
```

The following is incorrect:

``` python
if something
    something()
else
    something_else()
```

**Comment by bennuttall** [comment]
Or are you indenting incorrectly? The `if` and `else` should line up.

The following is incorrect:

``` python
if something:
    something()
    else:
        something_else()
```
